markdown: rdiscount
pygments: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: 头子
subTitle: 工作学习,永无止尽.
description: 这是 头子 的又一个博客，它是基于 Jekyll 搭建起来的。在这里，不仅仅是用来快速记录工作，学习，生活的一点一滴的地方，更是 头子 对 Jekyll 的学习和使用的一次有意义的实践。
url: http://touzi.github.io/ibnew
feed: /atom.xml
#个人信息的配置
qq: 305749023
name: 就叫我"头子"吧
email: policetouzi@163.com
github: touzi
weibo: 1622178027
about: "这里是 touzi 的个人博客，创建于 2014 年。2014年5月迁移到 Jekyll @ GitHub。<br /><br />职业coder，纯北漂，蜗居北京西城.这里包含了部分个人的“折腾”过程、结论和成果，切换到分类模可以更快地找到感兴趣的内容，欢迎观赏、建议、拍砖……"
#菜单配置
nav:
  - text: 首页
    url: /ibnew/index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /ibnew/archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /ibnew/contact.html
    #url: /ibnew/about/
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: https://twitter.com/policetouzi
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/touzi/ibnew
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: touzi
